version: 0.0
os: linux
files:
  - source: /
    destination: /home/
hooks:
  ApplicationStop:
    - location: scripts/stop_nodeserver.sh
      timeout: 300
  AfterInstall:
    - location: afterinstall.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 180
     
